// Generated by https://quicktype.io

export interface Planet {
    name:               string;
    diameter:           string;
    gravity:            string;
    climate:            string;
    orbital_period:     string;
    population:         string;
    rotation_period:    string;
    surface_water:      string;
    terrain:            string;
    url:                string;
}
